<?php

/**
 * @file
 * Custom hook into the honeycomb system.
 */

/**
 * ****Depreciated ***
 * Implements hook_page_alter();
 * USE - hook_page_attachments();
 */
function honeycomb_page_alter(&$page) {
  $page['#attached']['library'][] = 'honeycomb/honeycomb.all-pages';
}


/**
 * Implements hook_form_FORM_ID_alter()
 */
function honeycomb_form_photo_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Need to make some custom changes.

};

