<?php

/**
 * @file
 * Custom hook into the honeycomb system.
 */

include_once dirname(__FILE__) . '/honeycomb.theme.inc';

/**
 * ****Depreciated ***
 * Implements hook_page_alter();
 * USE - hook_page_attachments();
 */
function honeycomb_page_alter(&$page) {
  $page['#attached']['library'][] = 'honeycomb/honeycomb.all-pages';
}


/**
 * Implements hook_form_FORM_ID_alter()
 */
function honeycomb_form_photo_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Need to make some custom changes.

};

/**
 * Implements hook_theme();
 */
function honeycomb_theme() {
  return array(
    'company_profile' => array (
      'variables' => array('company' => NULL, 'images' => array()),
    ),
    'masonry_image' => array (
      'variables' => array('image_uri' => NULL, 'image_nid' => NULL, 'image_category_id' => NULL),
    ),
  );
};

